[package]
name = "fins-migrations-fairing"
version.workspace = true
license.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket.workspace = true
diesel_migrations.workspace = true
log = "0.4.17"
